# Generated by Django 3.2.18 on 2023-04-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.TextField(max_length=255)),
                ('latitude', models.IntegerField(null=True)),
                ('longitude', models.IntegerField(null=True)),
                ('tir_media', models.IntegerField(null=True)),
                ('total_captado', models.IntegerField(null=True)),
                ('vgv', models.IntegerField(null=True)),
            ],
        ),
    ]
