# Generated by Django 3.2.18 on 2023-04-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tir_media',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_captado',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='vgv',
            field=models.FloatField(null=True),
        ),
    ]
